Curriculum:
  StartMulti:
    mean_reward: 4.0
    episode_mean: 36
    cycles: 5
  Observe:
    mean_reward: -24.0
    episode_mean: 36
    cycles: 5
  NarrowDoorMulti:
    mean_reward: 4.5
    episode_mean: 36
    cycles: 10
  Corridor6:
    mean_reward: 5.0
    episode_mean: 36
    cycles: 10
  Stuck:
    mean_reward: -1.0
    episode_mean: 36
    cycles: 10
  CorridorPillar:
    mean_reward: 4.0
    episode_mean: 36
    cycles: 10
  2FCorridor:
    mean_reward: 4.0
    episode_mean: 36
    cycles: 15
  TurnsMulti:
    mean_reward: 30.0
    episode_mean: 36
    cycles: 10
  S:
    mean_reward: 5.0
    episode_mean: 36
    cycles: 10
  NarrowDoorDouble:
    mean_reward: 4.0
    episode_mean: 36
    cycles: 10

